version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: docker/java.dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: ["mvn spring-boot:run"]
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      PAGES_ALLOW_SUBDOMAINS: ${PAGES_ALLOW_SUBDOMAINS}
      USERS_FILE: ${USERS_FILE}
      BASE_URL: ${BASE_URL}
      PAGES_DOMAIN_NAME: ${PAGES_DOMAIN_NAME}
    tty: true
    ports:
      - "${APP_PORT}:8080"
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: pagebuilder
      POSTGRES_USER: pagebuilder
      POSTGRES_PASSWORD: password
    tty: true
    ports:
      - "${POSTGRES_PORT}:5432"
